#!/bin/sh

export IDS_SERVICE_USER_HOST=${IDS_SERVICE_USER_HOST:-ids.fzyun.io}
export IDS_SERVICE_USER_PORT=${IDS_SERVICE_USER_PORT:-8880}
export IDS_HOME_URL=${IDS_HOME_URL:-http://ids.fzyun.io:8089}
export IDS_KEYCLOAK_SERVERURL=${IDS_KEYCLOAK_SERVERURL:-http://ids.fzyun.io/auth}
export IDS_KEYCLOAK_ADMIN_USERNAME=${IDS_KEYCLOAK_ADMIN_USERNAME:-admin}
export IDS_KEYCLOAK_ADMIN_PASSWORD=${IDS_KEYCLOAK_ADMIN_PASSWORD:-admin}
export IDS_KEYCLOAK_COMPANY=${IDS_KEYCLOAK_COMPANY:-FounderID}
export KB_HOME_URL=${KB_HOME_URL:-http://kb.fzyun.net}
export SERVER_PORT=${SERVER:-8880}
export EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:-http://registry.fzyun.io/eureka}
export SPRING_APPLICATION_NAME=${SPRING_APPLICATION_NAME:-ids-service-user}
export SPRING_LOGSTASH_DESTINATION=${SPRING_LOGSTASH_DESTINATION:-kibana.fzyun.io}
export SPRING_RABBITMQ_HOST=${SPRING_RABBITMQ_HOST:-172.19.58.205}
export SPRING_RABBITMQ_PORT=${SPRING_RABBITMQ_PORT:-5672}
export SPRING_RABBITMQ_USERNAME=${SPRING_RABBITMQ_USERNAME:-guest}
export SPRING_RABBITMQ_PASSWORD=${SPRING_RABBITMQ_PASSWORD:-guest}
export SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL:-jdbc:mysql://ids.fzyun.io:3306/test?useUnicode=true&characterEncoding=UTF8}
export SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME:-root}
export SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD:-12345678}
export REDIS_HOST=${REDIS_HOST:-172.19.58.206}
export REDIS_PORT=${REDIS_PORT:-6379}
export REDIS_CHECK=${REDIS_CHECK:-true}

echo Enviroment Variables:
echo	IDS_SERVICE_USER_HOST=$IDS_SERVICE_USER_HOST
echo	IDS_SERVICE_USER_PORT=$IDS_SERVICE_USER_PORT
echo	IDS_HOME_URL=$IDS_HOME_URL
echo	IDS_KEYCLOAK_SERVERURL=$IDS_KEYCLOAK_SERVERURL
echo	IDS_KEYCLOAK_ADMIN_USERNAME=$IDS_KEYCLOAK_ADMIN_USERNAME
echo	IDS_KEYCLOAK_ADMIN_PASSWORD=$IDS_KEYCLOAK_ADMIN_PASSWORD
echo	IDS_KEYCLOAK_COMPANY=$IDS_KEYCLOAK_COMPANY
echo	KB_HOME_URL=$KB_HOME_URL
echo	SERVER_PORT=$SERVER_PORT
echo	EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=$EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
echo	SPRING_APPLICATION_NAME=$SPRING_APPLICATION_NAME
echo	SPRING_LOGSTASH_DESTINATION=$SPRING_LOGSTASH_DESTINATION
echo	SPRING_RABBITMQ_HOST=$SPRING_RABBITMQ_HOST
echo	SPRING_RABBITMQ_PORT=$SPRING_RABBITMQ_PORT
echo	SPRING_RABBITMQ_USERNAME=$SPRING_RABBITMQ_USERNAME
echo	SPRING_RABBITMQ_PASSWORD=$SPRING_RABBITMQ_PASSWORD
echo	SPRING_DATASOURCE_URL=$SPRING_DATASOURCE_URL
echo	SPRING_DATASOURCE_USERNAME=$SPRING_DATASOURCE_USERNAME
echo	SPRING_DATASOURCE_PASSWORD=$SPRING_DATASOURCE_PASSWORD
echo	REDIS_HOST=$REDIS_HOST
echo	REDIS_PORT=$REDIS_PORT
echo	REDIS_CHECK=$REDIS_CHECK
