ids:
    home:
        url: ${IDS_HOME_URL:http://ids-admin.fzyun.io}
    keycloak:
        serverUrl: ${IDS_KEYCLOAK_SERVERURL:http://kc.kc.dev.fzyun.io/auth}
        admin:
            username: ${IDS_KEYCLOAK_ADMIN_USERNAME:admin}
            password: ${IDS_KEYCLOAK_ADMIN_PASSWORD:admin}
        company: ${IDS_KEYCLOAK_COMPANY:FounderID}
kb:
    home:
        url: ${KB_HOME_URL:http://kb.fzyun.net}
server:
    port: ${SERVER_PORT:8880}
eureka:
    client:
        healthcheck:
            enabled: true
        serviceUrl:
            defaultZone: ${EUREKA_REGISTRY_URL:http://registry.service-governance/eureka}
    instance:
        lease-expiration-duration-in-seconds: 9
        lease-renewal-interval-in-seconds: 3
        #prefer-ip-address: true
        #ip-address: ${spring.cloud.client.ipAddress}
        #instance-id: ${eureka.instance.ip-address}:${server.port}:${spring.application.name}
spring:
    application:
        name: ids-service-user
    rabbitmq:
        host: ${SPRING_RABBITMQ_HOST:rabbitmq.rabbitmq}
        port: ${SPRING_RABBITMQ_PORT:5672}
        username: ${SPRING_RABBITMQ_USERNAME:founder}
        password: ${SPRING_RABBITMQ_PASSWORD:Founder123}
        publisher-confirms: true
        virtual-host: /
    datasource:
        name: ${spring.application.name}
        url: ${SPRING_DATASOURCE_URL:jdbc:mysql://db/ids?useUnicode=true&characterEncoding=UTF8}
        username: ${SPRING_DATASOURCE_USERNAME:root}
        password: ${SPRING_DATASOURCE_PASSWORD:root}
        driver-class-name: com.mysql.jdbc.Driver
        initialSize: 5
        minIdle: 5
        maxActive: 20
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
        filters: stat
        manager:
            url: /druid/*
            username: druid
            password: 123456
exception:
    center:
        open: true
redis:
    host: ${REDIS_HOST:redis}
    port: ${REDIS_PORT:6379}
    check: ${REDIS_CHECK:true}
