version: "3"
services:
    idsServiceUser:
        image: hub.fzyun.io/founder/ids-service-user:${ids_tag:-latest}
        container_name: ids-service-user
        environment:
            - IDS_SET_EXTERNAL_CONFIG=1
            - IDS_PROFILE=production
        volumes:
            - $WORKSPACE/config:/opt/ids/config
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
        ports:
            - 8880:8880
